#!/usr/bin/env bash
# set -x
#
# Runs the Lexicalized Parser GUI.  You can just run this script and then
# load a grammar and file to be parsed from the menus or you can specify
# them on the command line.
#
# Usage: ./lexparser-gui [parserDataFilename [textFileName]]
#


(
	CURR_PWD=${PWD}
	cd $(dirname $0)
	SCRIPT_PWD=${PWD}

    if [[ ""$SP_CLASSPATH"" == """" ]]
    then
        LIB=${SCRIPT_PWD}/../lib
        JARS=($(find $LIB -type f -name "*.jar"))
        for index in "${!JARS[@]}"
        do
            if [ $index -eq 0 ]
            then
                SP_CLASSPATH=${JARS[$index]}
            else
                SP_CLASSPATH="$SP_CLASSPATH:${JARS[$index]}"
            fi
        done
    fi

    cd $LIB
    java -mx800m -cp $SP_CLASSPATH edu.stanford.nlp.parser.ui.Parser $*
	cd $CURR_PWD

)

