#!/usr/bin/env bash
# set -x
#
# Runs the English PCFG parser on one or more files, printing trees only

if [ ! $# -ge 1 ]; then
  echo Usage: `basename $0` 'file(s)'
  echo
  exit
fi

(
	CURR_PWD=${PWD}
	cd $(dirname $0)
	SCRIPT_PWD=${PWD}
	
	if [[ ""$LEXMODEL"" == """" ]]
	then
		LEXMODEL="edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz"
	fi

	if [[ ""$SP_CLASSPATH"" == """" ]]
	then
		LIB=${SCRIPT_PWD}/../lib
		JARS=($(find $LIB -type f -name "*.jar"))
		for index in "${!JARS[@]}"
		do
			if [ $index -eq 0 ]
			then
				SP_CLASSPATH=${JARS[$index]}
			else
				SP_CLASSPATH="$SP_CLASSPATH:${JARS[$index]}"
			fi
		done
	fi
	
	java -mx150m -cp ${SP_CLASSPATH} edu.stanford.nlp.parser.lexparser.LexicalizedParser -outputFormat "penn,typedDependencies" $LEXMODEL $*

	cd $CURR_PWD
)
